name: Build

on:
  push:
    paths-ignore:
      - '.git**'
      - '**.md'
      - 'LICENSE'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4

      - name: Build project
        run: |
          make build
          echo "version=$(git describe --always)" >> $GITHUB_ENV

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: 'nvg_${{ env.version }}'
          path: |
            build/output/nvg
